//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLKI.Programme.FDA.src {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class resMainForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal resMainForm() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OLKI.Programme.FDA.src.resMainForm", typeof(resMainForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stapelverarbeitung ähnelt.
        /// </summary>
        internal static string btnBatchStart_Click_Exception_Caption {
            get {
                return ResourceManager.GetString("btnBatchStart_Click_Exception_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wärend der Stapelverarbeitung ist ein Fehler aufgetreten. Es konnte einige oder alle Dateien nicht bearbeitet werden.
        ///
        ///Fehler:
        ///{0} ähnelt.
        /// </summary>
        internal static string btnBatchStart_Click_Exception_Message {
            get {
                return ResourceManager.GetString("btnBatchStart_Click_Exception_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausführung als Administrator ähnelt.
        /// </summary>
        internal static string btnCheckForAdminRights_Click__IsAdmin_Caption {
            get {
                return ResourceManager.GetString("btnCheckForAdminRights_Click__IsAdmin_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie führen dieses Programm als Administrator aus. ähnelt.
        /// </summary>
        internal static string btnCheckForAdminRights_Click__IsAdmin_Message {
            get {
                return ResourceManager.GetString("btnCheckForAdminRights_Click__IsAdmin_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte als Administrator auführen ähnelt.
        /// </summary>
        internal static string btnCheckForAdminRights_Click__IsNotAdmin_Caption {
            get {
                return ResourceManager.GetString("btnCheckForAdminRights_Click__IsNotAdmin_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie sollten die Anwendung als Administrator ausführen um Fehler aufgrund verweigerter Zugriffsrechte zu vermeiden. ähnelt.
        /// </summary>
        internal static string btnCheckForAdminRights_Click__IsNotAdmin_Message {
            get {
                return ResourceManager.GetString("btnCheckForAdminRights_Click__IsNotAdmin_Message", resourceCulture);
            }
        }
    }
}
